name: Build

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
        build:
          - name: std
          - name: no-std
            cargo_build_target: thumbv8m.main-none-eabi
    steps:
    - uses: actions/checkout@v5
    - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
    - name: install target
      if: ${{ matrix.build.cargo_build_target }}
      run: rustup target add ${{ matrix.build.cargo_build_target }}
    - name: build tropic01
      run: |
        if [ -n "${{ matrix.build.cargo_build_target }}" ]; then
          export CARGO_BUILD_TARGET=${{ matrix.build.cargo_build_target }}
        fi
        cargo build --package tropic01 --no-default-features
        cargo build --package tropic01
        cargo build --package tropic01 --all-features
    - name: build tropic01-example-rpi
      if: ${{ matrix.build.name == 'std' }}
      run: |
        cargo build --package tropic01-example-rpi
